# Generated by Django 3.2.16 on 2022-12-31 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(help_text='Phone number must be in the format +991112223', max_length=18, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format:             '+999999999'. Up to 15 digits allowed.", regex='^\\+\\d{8,17}$')]),
        ),
    ]
