# Generated by Django 3.2.16 on 2023-01-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_alter_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_shipped',
            field=models.BooleanField(default=False),
        ),
    ]
