# Generated by Django 3.2.16 on 2023-01-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-name',)},
        ),
    ]
